services:
  fastapi:
    build: .
    container_name: fakenews-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped